jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      mkdir build && cd build
      curl -LO https://github.com/bow-simulation/virtualbow-dependencies/releases/download/v1.3/windows-mingw_64.zip && 7z x windows-mingw_64.zip
      cmake ../ -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=windows-mingw_64/paths.cmake
      cmake --build . -j%NUMBER_OF_PROCESSORS%
      cmake --build . --target iss-installer -j%NUMBER_OF_PROCESSORS%
      virtualbow-test
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/application'
      artifactName: 'windows-application'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/packages'
      artifactName: 'windows-packages'
      
- job: MacOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - script: |
      npm install -g appdmg@0.6.0 --no-audit
      mkdir build && cd build
      curl -LO https://github.com/bow-simulation/virtualbow-dependencies/releases/download/v1.3/macos-clang_64.zip && unzip macos-clang_64.zip
      cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=macos-clang_64/paths.cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13
      cmake --build .
      cmake --build . --target dmg-installer
      ./virtualbow-test
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/application'
      artifactName: 'macos-application'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/packages'
      artifactName: 'macos-packages'

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    CC: gcc-9
    CXX: g++-9
  steps:
  - script: |
      sudo apt update -qq && sudo apt install -y qtbase5-dev libqt5x11extras5-dev libgl1-mesa-dev
      mkdir build && cd build
      curl -LO https://github.com/bow-simulation/virtualbow-dependencies/releases/download/v1.3/linux-gcc_64.zip && unzip linux-gcc_64.zip
      cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=linux-gcc_64/paths.cmake
      cmake --build . -j$(nproc)
      cmake --build . --target deb-package -j$(nproc)
      cmake --build . --target rpm-package -j$(nproc)
      ./virtualbow-test
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/application'
      artifactName: 'linux-application'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/packages'
      artifactName: 'linux-packages'
